### ISSUE TITLE
Main weapon / offhand not in shared link

### ISSUE THREAD

**Issue by Shadowtrance** [MrEliasen/BDO-Gear-Calculator#3]
As per title, testing your current changes and it seems the main weapon and secondary weapon aren't appearing in shared links for some reason.
For example, here i had a liverto shortsword and needle trinket equipped, but they are nowhere to be seen using the generated link. https://www.sirmre.com/bdo-gear-calculator/?gear=[3,[10,15,[19,19]],[11,15,[23,23]],[10,15,[11,11]],[10,15,[5,11]],[[30,0],[30,0]],[[28,0],[28,0]],[14,1],[7,3],[-1,15,[29,29]],[-1,15,[11,-1]]]

Also looking forward to the app version (hopefully android :P ), how goes the progress on that so far? :)

Edit: just remembered, not seeing any tooltips either for slots on hover either.

**Comment by MrEliasen** [comment]
Thanks for letting me know, I will look into it.
I do not think I had tooltips on the slots, regardless, I will investigate!

**Comment by MrEliasen** [comment]
Really sorry about the long delay, it should be fixed now.
I know it's annoying, but old share links are not working - new once will need to be remade.

**Comment by Shadowtrance** [comment]
Such a simple fix so easily missed. haha always the way. i know i missed it, but my js skills are not that great either. :)
Only other issue I've noticed is the "all" slot crystals (eg: luck, armor etc) don't show up at all in any crystal slots for anything.

**Comment by MrEliasen** [comment]
Good catch, I will investigate!

**Comment by MrEliasen** [comment]
This should be fixed now. Thanks again for letting me know!

**Comment by Shadowtrance** [comment]
That was quick! :)
Seems only partially fixed though, they now show up in the crystal selection list as they should but the crystal box/image border doesn't change color like the others and the stats they give don't seem to show in the stats list on the side either (where it shows attack speed etc).

Besides that small issue i can't say i can see anything else wrong with it at the moment. :) I'm going to do some work on updating the database soon i think seeing as the only other gear calc i know of hasn't been updated in a while and isn't open source.

Wish i knew js better so i could fix issues myself to be honest instead of bugging you. haha Great work btw, updating the database will keep me busy for a while. :)

**Comment by MrEliasen** [comment]
Looks like I pushed the fix a bit too quick then!
I am at work, thought I would do it while having lunch, will give it a proper look once I get home.

Much appreciated! Help with the DB is always welcome. If you want me to help you with how the DB is put together just let me know and I will guide you though to the best of my abilities :)

**Comment by Shadowtrance** [comment]
Yeah any tips regarding the db couldn't hurt. Think i have it figured out for the most part. :)
I've got it running on my own raspberry pi webserver atm with some changes to it and some db updates. As you should be able to see here. 

http://shadowtrance.noip.me/bdo2/?gear=[11,[9,15,[19,19]],[9,16,[23,23]],[9,15,[11,11]],[9,15,[5,12]],[[26,1],[26,1]],[[23,0],[23,0]],[9,2],[7,3],[12,16,[29,27]],[4,16,[-1,-1]]]

As you can see in that link, the offhand is supposed to have a +1 luck crystal but it doesn't seem to take. So it only seems to be affecting the "all" slots crystals and not the others from what i can see.

**Comment by MrEliasen** [comment]
Hi again,

Sorry for the belated response, I just recovered from about a week of illness. I have to catch up on work this week but will look at the gem bug as soon as possible.

**Comment by Shadowtrance** [comment]
Seems we both got busy with life. haha Had some time to mess with it a bit, found where the issue is with the "all" crystals not working when selected for a slot, not sure how to fix it. Slowly adding/making changes to the database as well. :)
Hopefully you're still around. :)

Anyway, when i select an "all" slot crystal this is the error thrown in chrome console.

> Uncaught TypeError: Cannot read property 'rarity' of undefined
>     at setGearslotItem (http://shadowtrance.noip.me/bdo4/assets/js/app.js:248:46)
>     at http://shadowtrance.noip.me/bdo4/assets/js/app.js:289:13
>     at Object.setGear (http://shadowtrance.noip.me/bdo4/assets/js/bdo_calculator.js:183:9)
>     at addItem (http://shadowtrance.noip.me/bdo4/assets/js/app.js:288:23)
>     at HTMLButtonElement.<anonymous> (http://shadowtrance.noip.me/bdo4/assets/js/app.js:545:13)
>     at HTMLDocument.dispatch (https://code.jquery.com/jquery-2.2.3.min.js:3:7537)
>     at HTMLDocument.r.handle (https://code.jquery.com/jquery-2.2.3.min.js:3:5620)

Also, the calculated min AP seems to be off by 2 (adding 2 to the calculated amount = what is shown on character sheet it seems). I guess they take the middle point of mainhand weapon AP for that, rather than the min. Just a guess.

**Comment by MrEliasen** [comment]
Oh crap, yes I am well deep in work and real life events (about to move, new job etc).
I cannot promise much right now, as time is scarce, but if you can find how to fix this; feel free to send a pull request. :)

Correct, the weapons will avg. from its AP range, since it not possible to determine where you will end up in game (at least not at the time of writing).

**Comment by Shadowtrance** [comment]
Yeah fair enough. damn you real life! always getting in the way. haha

Yeah i wish they had an api available for these sort of things, sadly there isn't (yet), probably won't ever be. So we just have to guess. haha

Oh, another thing i just remembered, if i copy one of the offending "all" crystals to say the secondary weapon crystal section (and remove it from "all") it works as it should. Probably not helpful, but anyway...

**Comment by Shadowtrance** [comment]
Safe to say this issue is gone now. :)
